//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.base;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       The Attribute element is an abstract element. Useful attributes
 *       (ones that include fields) must be derived from the Attribute element
 *       defined within this schema. The derived attributes will define their 
 *       data elements to represent data fields.
 *     
 *       The derived attributes also need to be set as 'equivalent' to the 
 *       Attribute element. This enables the new derived attribute to be
 *       inserted into documents wherever the Attribute element is allowed.
 *       
 * 
 * <p>Java class for AttributeBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}DescriptionBase">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AttributeBase")
public abstract class AttributeBase extends DescriptionBase {
    
    public AttributeBase(Node node) {
        super(node);
    }


}
