//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tcadminview.plmxmlpdm.type;

import tcadminview.plmxmlpdm.TagTools;
import tcadminview.plmxmlpdm.base.AttributeBase;
import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       plm:Attribute used to associate a Form with a PLM XML element.
 *       
 *       Attributes:
 *       
 *       formRef      reference to the Form
 *       role         role/purpose of Form.    
 *       
 * 
 * <p>Java class for AssociatedFormType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedFormType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttributeBase">
 *       &lt;attribute name="formRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AssociatedFormType")
public class AssociatedFormType extends AttributeBase {

    //@XmlAttribute(required = true)
    protected final String formRefAttribute = "formRef";
    protected String formRef;

    //@XmlAttribute
    protected final String roleAttribute = "role";
    protected String role;
    
    
    public AssociatedFormType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
       
        setFormRef(TagTools.getStringValue(attrib, formRefAttribute));
        setRole(TagTools.getStringValue(attrib, roleAttribute));
    }

    /**
     * Gets the value of the formRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormRef() {
        return formRef;
    }

    /**
     * Sets the value of the formRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormRef(String value) {
        this.formRef = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
