//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tcadminview.plmxmlpdm.type;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tcadminview.plmxmlpdm.*;
import tcadminview.plmxmlpdm.base.AttributeBase;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       Attribute used to associate a DataSet with a PLM XML element.
 * 
 *       Attributes:
 *       
 *       dataSetRef: uri reference to DataSet
 *       role:       role/purpose of DataSet. No specified values.
 *       
 * 
 * <p>Java class for AssociatedDataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedDataSetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttributeBase">
 *       &lt;attribute name="dataSetRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AssociatedDataSetType")
public class AssociatedDataSetType extends AttributeBase {

    //@XmlAttribute(required = true)
    protected final String dataSetRefAttribute = "dataSetRef";
    protected String dataSetRef;
    
    //@XmlAttribute(required = true)
    protected final String roleAttribute = "role";
    protected String role;

    
    public AssociatedDataSetType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();

        setDataSetRef(
                TagTools.getStringValue(attrib, dataSetRefAttribute));
        setRole(
                TagTools.getStringValue(attrib, roleAttribute));
    }
    
    /**
     * Gets the value of the dataSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetRef() {
        return dataSetRef;
    }

    /**
     * Sets the value of the dataSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetRef(String value) {
        this.dataSetRef = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
