//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tcadminview.plmxmlpdm.type;

import java.util.ArrayList;
import java.util.List;
import tcadminview.plmxmlpdm.*;

import tcadminview.plmxmlpdm.TagTools;
import tcadminview.plmxmlpdm.base.AttributeBase;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tcadminview.plmxmlpdm.type.element.ValidationCheckerType;

/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       This element, derived from plm:Attribute, is used to give the results of applying
 *       a validation check to its parent element.
 *         
 *       Attributes:
 *       
 *       application:      the validating application
 *       
 *       Sub-elements:
 *       
 *       Checker:          the name and result of each check performed
 *       
 * 
 * <p>Java class for ValidationResultsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationResultsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttributeBase">
 *       &lt;sequence>
 *         &lt;element name="Checker" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}ValidationCheckerType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="application" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
/*
 @XmlType(name = "ValidationResultsType", propOrder = {
    "checker"
})
 */
public class ValidationResultsType extends AttributeBase {

    //@XmlElement(name = "Checker", required = true)
    protected List<ValidationCheckerType> checker;
    
    //@XmlAttribute
    protected final String applicationAttribute = "application";
    protected String application;

    
    public ValidationResultsType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();
        
        setApplication(TagTools.getStringValue(attrib, applicationAttribute));
        
        TagTypeEnum tagType;
        for (int i=0; i<nodeList.getLength(); i++) {
            currentNode = nodeList.item(i);
            tagType = TagTypeEnum.fromValue(currentNode.getNodeName());
            
            switch(tagType) {
                case Checker:
                    getChecker().add(new ValidationCheckerType(currentNode));
                    break;
                    
                default:
                    break;
            }
        }
    } 
    /**
     * Gets the value of the checker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChecker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidationCheckerType }
     * 
     * 
     */
    public List<ValidationCheckerType> getChecker() {
        if (checker == null) {
            checker = new ArrayList<ValidationCheckerType>();
        }
        return this.checker;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

}
