//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tcav.plmxmlpdm.type;

import java.util.ArrayList;
import java.util.List;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tcav.plmxmlpdm.base.AccessControlBase;
import tcav.plmxmlpdm.classtype.AccessIntentEnum;
import tcav.plmxmlpdm.*;

/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       Simple access control element. Specifies a set of owners, and read/write access.
 *       
 *       Attributes:
 *  
 *       intent:      reference, modifiable or noAccess.
 *       ownerRefs    Reference to one or more owners. These should be elements 
 *                    derived from plm:OwnerBase, e.g. Person, Organisation, Site, etc.
 *       
 * 
 * <p>Java class for AccessIntentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessIntentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AccessControlBase">
 *       &lt;attribute name="intent" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}AccessIntentEnum" default="modifiable" />
 *       &lt;attribute name="ownerRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AccessIntentType")
public class AccessIntentType extends AccessControlBase {

    //@XmlAttribute
    protected final String AccessIntentEnumAttribute = "AccessIntentEnum";
    protected AccessIntentEnum intent;
    
    //@XmlAttribute
    protected final String ownerRefsAttribute = "ownerRefs";
    protected List<String> ownerRefs;
    
    public AccessIntentType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        
        TagTools.addToList(attrib, ownerRefsAttribute, getOwnerRefs());
        
        String s;
        
        s = TagTools.getStringValue(attrib, AccessIntentEnumAttribute);
        if(s != null)
            setIntent(AccessIntentEnum.fromValue(s));
    }

    /**
     * Gets the value of the intent property.
     * 
     * @return
     *     possible object is
     *     {@link AccessIntentEnum }
     *     
     */
    public AccessIntentEnum getIntent() {
        if (intent == null) {
            return AccessIntentEnum.MODIFIABLE;
        } else {
            return intent;
        }
    }

    /**
     * Sets the value of the intent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessIntentEnum }
     *     
     */
    public void setIntent(AccessIntentEnum value) {
        this.intent = value;
    }

    /**
     * Gets the value of the ownerRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownerRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOwnerRefs() {
        if (ownerRefs == null) {
            ownerRefs = new ArrayList<String>();
        }
        return this.ownerRefs;
    }

}
