//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tcav.plmxmlpdm.type;

import tcav.plmxmlpdm.TagTools;
import tcav.plmxmlpdm.base.AttributeBase;
import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       plm:Attribute used to associate a Folder with a PLM XML element.
 *       
 *       Attributes:
 *       
 *       folderRef     reference to the Folder
 *       role          role/purpose of Folder.
 *       
 * 
 * <p>Java class for AssociatedFolderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedFolderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttributeBase">
 *       &lt;attribute name="folderRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AssociatedFolderType")
public class AssociatedFolderType extends AttributeBase {

    //@XmlAttribute(required = true)
    protected final String folderRefAttribute = "folderRef";
    protected String folderRef;

    //@XmlAttribute
    protected final String roleAttribute = "role";
    protected String role;
    
    
    public AssociatedFolderType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
       
        setFolderRef(TagTools.getStringValue(attrib, folderRefAttribute));
        setRole(TagTools.getStringValue(attrib, roleAttribute));
    }

    /**
     * Gets the value of the folderRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderRef() {
        return folderRef;
    }

    /**
     * Sets the value of the folderRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderRef(String value) {
        this.folderRef = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
