//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.UnusedRequiredTags;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import tceav.manager.procedure.plmxmlpdm.base.AttribOwnerBase;
import org.w3c.dom.Node;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
*/

/**
 * 
 *       ReleaseStatus. Specifies date of release, and effectivities.
 * 
 *       Attributes:
 *       
 *       dateReleased:    Date and time released.
 *       effectivityRefs: Reference to Effectivity elements.
 *       
 * 
 * <p>Java class for ReleaseStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseStatusType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttribOwnerBase">
 *       &lt;attribute name="dateReleased" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="effectivityRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "ReleaseStatusType")
public class ReleaseStatusType extends AttribOwnerBase {

    //@XmlAttribute
    protected Date dateReleased;
    //@XmlAttribute
    protected List<String> effectivityRefs;
    
    public ReleaseStatusType(Node node) {
        super(node);
    }

    /**
     * Gets the value of the dateReleased property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDateReleased() {
        return dateReleased;
    }

    /**
     * Sets the value of the dateReleased property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReleased(Date value) {
        this.dateReleased = value;
    }

    /**
     * Gets the value of the effectivityRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectivityRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectivityRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEffectivityRefs() {
        if (effectivityRefs == null) {
            effectivityRefs = new ArrayList<String>();
        }
        return this.effectivityRefs;
    }

}
