//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.UnusedRequiredTags;

import java.util.ArrayList;
import java.util.List;
import tceav.manager.procedure.plmxmlpdm.base.AttribOwnerBase;
import org.w3c.dom.Node;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       A base type for defining relations between workflow task template and signoff profile elements. 
 *       ownerRef is a reference to an owning object, such as a task template or a task. profileRefs is 
 *       a reference to one or many signoff profiles that this owner object is associated to.
 *       
 * 
 * <p>Java class for WorkflowProfileRelationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowProfileRelationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttribOwnerBase">
 *       &lt;attribute name="ownerRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="profileRefs" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "WorkflowProfileRelationType")
public class WorkflowProfileRelationType extends AttribOwnerBase {

    //@XmlAttribute(required = true)
    protected String ownerRef;
    //@XmlAttribute(required = true)
    protected List<String> profileRefs;
    
    
    public WorkflowProfileRelationType(Node node) {
        super(node);
    }

    /**
     * Gets the value of the ownerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerRef() {
        return ownerRef;
    }

    /**
     * Sets the value of the ownerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerRef(String value) {
        this.ownerRef = value;
    }

    /**
     * Gets the value of the profileRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProfileRefs() {
        if (profileRefs == null) {
            profileRefs = new ArrayList<String>();
        }
        return this.profileRefs;
    }

}
