//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type;

import java.util.ArrayList;
import java.util.List;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.AccessControlBase;
import tceav.manager.procedure.plmxmlpdm.classtype.AccessIntentEnum;

/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       Simple access control element. Specifies a set of owners, and read/write access.
 *       
 *       Attributes:
 *  
 *       intent:      reference, modifiable or noAccess.
 *       ownerRefs    Reference to one or more owners. These should be elements 
 *                    derived from plm:OwnerBase, e.g. Person, Organisation, Site, etc.
 *       
 * 
 * <p>Java class for AccessIntentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessIntentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AccessControlBase">
 *       &lt;attribute name="intent" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}AccessIntentEnum" default="modifiable" />
 *       &lt;attribute name="ownerRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AccessIntentType")
public class AccessIntentType extends AccessControlBase {

    //@XmlAttribute
    protected final String AccessIntentEnumAttribute = "AccessIntentEnum";
    protected AccessIntentEnum intent;
    
    //@XmlAttribute
    protected final String ownerRefsAttribute = "ownerRefs";
    protected List<String> ownerRefs;
    
    public AccessIntentType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        
        TagTools.addToList(attrib, ownerRefsAttribute, getOwnerRefs());
        
        String s;
        
        s = TagTools.getStringValue(attrib, AccessIntentEnumAttribute);
        if(s != null)
            setIntent(AccessIntentEnum.fromValue(s));
    }

    public AccessIntentEnum getIntent() {
        if (intent == null) {
            return AccessIntentEnum.MODIFIABLE;
        } else {
            return intent;
        }
    }

    public void setIntent(AccessIntentEnum value) {
        this.intent = value;
    }

    public List<String> getOwnerRefs() {
        if (ownerRefs == null) {
            ownerRefs = new ArrayList<String>();
        }
        return this.ownerRefs;
    }
    
    /***************
     * Customisation
     ***************/
    protected SiteType owner;
    
    public SiteType getOwner() {
        return owner;
    }
    
    public void setOwner(SiteType owner) {
        this.owner = owner;
    }

}
