//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type;

import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.AttributeBase;
import tceav.manager.procedure.plmxmlpdm.base.IdBase;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;

/**
 * 
 *       Attribute used to associate a DataSet with a PLM XML element.
 * 
 *       Attributes:
 *       
 *       dataSetRef: uri reference to DataSet
 *       role:       role/purpose of DataSet. No specified values.
 *       
 * 
 * <p>Java class for AssociatedDataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedDataSetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttributeBase">
 *       &lt;attribute name="dataSetRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "AssociatedDataSetType")
public class AssociatedDataSetType extends AttributeBase {

    //@XmlAttribute(required = true)
    protected final String dataSetRefAttribute = "dataSetRef";
    protected String dataSetRef;
    
    //@XmlAttribute(required = true)
    protected final String roleAttribute = "role";
    protected String role;

    
    public AssociatedDataSetType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();

        setDataSetRef(TagTools.getStringValue(attrib, dataSetRefAttribute));
        setRole(TagTools.getStringValue(attrib, roleAttribute));
    }
    
    public String getDataSetRef() {
        return dataSetRef;
    }

    public void setDataSetRef(String value) {
        this.dataSetRef = value;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String value) {
        this.role = value;
    }

    /***************
     * Customisation
     ***************/
    private IdBase dataSet;
    
    public IdBase getDataSet() {
        return dataSet;
    }

    public void setDataSet(IdBase dataSet) {
        this.dataSet = dataSet;
    }
}
