//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type;

import java.util.ArrayList;
import java.util.List;
import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.OwnerBase;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       An organisation, i.e. a group of people or users. Organisations are hierarchical.
 *       People/Users are associated with organisations by means of an OrganisationMember 
 *       element, which also specifies a Role.
 * 
 *       Attributes:
 * 
 *       (name:            Name, inherited from DescriptionBase)
 *       address:          Optional reference to Address.
 *       organisationRefs: Reference to sub-organisations.
 *       cageCode:         CAGE code (5 characters). This is a US government company code.
 *       
 * 
 * <p>Java class for OrganisationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganisationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}OwnerBase">
 *       &lt;attribute name="addressRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="cageCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="organisationRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "OrganisationType")
public class OrganisationType extends OwnerBase {

    //@XmlAttribute
    protected final String addressRefAttribute = "addressRef";
    protected String addressRef;
    
    //@XmlAttribute
    protected final String cageCodeAttribute = "cageCode";
    protected String cageCode;
    
    //@XmlAttribute
    protected final String organisationRefsAttribute = "organisationRefs";
    protected List<String> organisationRefs;
    
    
    public OrganisationType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();

        setAddressRef(TagTools.getStringValue(attrib, addressRefAttribute));
        setCageCode(TagTools.getStringValue(attrib, cageCodeAttribute));
        
        TagTools.addToList(attrib, organisationRefsAttribute, getOrganisationRefs());
    }

    public String getAddressRef() {
        return addressRef;
    }

    public void setAddressRef(String value) {
        this.addressRef = value;
    }

    public String getCageCode() {
        return cageCode;
    }

    public void setCageCode(String value) {
        this.cageCode = value;
    }

    public List<String> getOrganisationRefs() {
        if (organisationRefs == null) {
            organisationRefs = new ArrayList<String>();
        }
        return this.organisationRefs;
    }

    /***************
     * Customisation
     ***************/
    private OrganisationType[] subOrganisations;
    
    public OrganisationType[] getSubOrganisations() {
        if(subOrganisations == null)
            subOrganisations = new OrganisationType[getOrganisationRefs().size()];
        
        return subOrganisations;
    }
}
