//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type;

import java.util.ArrayList;
import java.util.List;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.AttribOwnerBase;

import tceav.manager.procedure.plmxmlpdm.classtype.WorkflowActionTypeEnum;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       Each WorkflowAction object has one or more action handlers and business rules associated
 *       with it. The action handlers are represented by a list WorkflowHandlers, while the business
 *       rules are represented WorkflowBusinessRules. The WorkflowAction object also has a back pointer
 *       to its parent task template.
 *       
 * 
 * <p>Java class for WorkflowActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowActionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttribOwnerBase">
 *       &lt;attribute name="actionHandlerRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *       &lt;attribute name="actionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentRef" use="required" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="ruleRefs" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}uriReferenceListType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "WorkflowActionType")
public class WorkflowActionType extends AttribOwnerBase {

    //@XmlAttribute
    protected final String actionHandlerRefsAttribute = "actionHandlerRefs";
    protected List<String> actionHandlerRefs;
    
    //@XmlAttribute(required = true)
    protected String actionTypeAttribute = "actionType";
    protected String actionType;
    
    //@XmlAttribute(required = true)
    protected final String parentRefAttribute = "parentRef";
    protected String parentRef;
    
    //@XmlAttribute
    protected final String ruleRefsAttribute = "ruleRefs";
    protected List<String> ruleRefs;
    
    public WorkflowActionType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();
        
        setActionType(TagTools.getStringValue(attrib, actionTypeAttribute));
        setParentRef(TagTools.getStringValue(attrib, parentRefAttribute));

        TagTools.addToList(attrib, actionHandlerRefsAttribute, getActionHandlerRefs());
        TagTools.addToList(attrib, ruleRefsAttribute, getRuleRefs());
    }
    
    public List<String> getActionHandlerRefs() {
        if (actionHandlerRefs == null) {
            actionHandlerRefs = new ArrayList<String>();
        }
        return this.actionHandlerRefs;
    }

    public String getActionType() {
        return actionType;
    }

    public String getParentRef() {
        return parentRef;
    }

    public void setParentRef(String value) {
        this.parentRef = value;
    }

    public List<String> getRuleRefs() {
        if (ruleRefs == null) {
            ruleRefs = new ArrayList<String>();
        }
        return this.ruleRefs;
    }
    
    /***************
     * Customisation
     ***************/

    private WorkflowHandlerType[] handlers;
    private WorkflowBusinessRuleType[] businessRules;
    protected WorkflowActionTypeEnum type;
    
    
    public WorkflowActionTypeEnum getType() {
        return type;
    }

    public void setActionType(String value) {
        this.actionType = value;
        type = WorkflowActionTypeEnum.fromValue(value);
    }
    
    public WorkflowHandlerType[] getActionHandlers() {
        if(handlers == null)
            handlers = new WorkflowHandlerType[getActionHandlerRefs().size()];
        return handlers;
    }

    public WorkflowBusinessRuleType[] getRules() {
        if(businessRules == null)
            businessRules = new WorkflowBusinessRuleType[getRuleRefs().size()];
        return businessRules;
    }
    
}
