//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type;

import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.AttribOwnerBase;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;

/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       A WorkflowSignoffProfile is used in a workflow review task template to define which a 
 *       user will comply with to assign review responsibilities to other Users. A signoff profile
 *       consists of a group and a role for a user, while the group object should be of type 
 *       plm:OrganisationType, and the role object should be of type plm:RoleType. The signoff profile
 *       object also has a back pointer to its related task template.
 *       
 * 
 * <p>Java class for WorkflowSignoffProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowSignoffProfileType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}AttribOwnerBase">
 *       &lt;attribute name="allowSubgroups" use="required" type="{http://www.w3.org/2001/XMLSchema}Boolean" />
 *       &lt;attribute name="groupRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="numberOfSignoffs" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="roleRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="signoffQuorum" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="templateRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "WorkflowSignoffProfileType")
public class WorkflowSignoffProfileType extends AttribOwnerBase {

    //@XmlAttribute(required = true)
    protected final String allowSubgroupsAttribute = "allowSubgroups";
    protected Boolean allowSubgroups;
    
    //@XmlAttribute
    protected final String groupRefAttribute = "groupRef";
    protected String groupRef;
    
    //@XmlAttribute(required = true)
    protected final String numberOfSignoffsAttribute = "numberOfSignoffs";
    protected Integer numberOfSignoffs;
    
    //@XmlAttribute
    protected final String roleRefAttribute = "roleRef";
    protected String roleRef;
    
    //@XmlAttribute(required = true)
    protected final String signoffQuorumAttribute = "signoffQuorum";
    protected Integer signoffQuorum;
    
    //@XmlAttribute
    protected final String templateRefAttribute = "templateRef";
    protected String templateRef;
    
    
    public WorkflowSignoffProfileType(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();

        setAllowSubgroups(TagTools.getBooleanValue(attrib, allowSubgroupsAttribute));
        setGroupRef(TagTools.getStringValue(attrib, groupRefAttribute));
        setNumberOfSignoffs(TagTools.getIntegerValue(attrib, numberOfSignoffsAttribute));
        setRoleRef(TagTools.getStringValue(attrib, roleRefAttribute));
        setSignoffQuorum(TagTools.getIntegerValue(attrib, signoffQuorumAttribute));
        setTemplateRef(TagTools.getStringValue(attrib, templateRefAttribute));
    }

    public Boolean isAllowSubgroups() {
        return allowSubgroups;
    }

    public void setAllowSubgroups(Boolean value) {
        this.allowSubgroups = value;
    }

    public String getGroupRef() {
        return groupRef;
    }

    public void setGroupRef(String value) {
        this.groupRef = value;
    }

    public Integer getNumberOfSignoffs() {
        return numberOfSignoffs;
    }

    public void setNumberOfSignoffs(Integer value) {
        this.numberOfSignoffs = value;
    }

    public String getRoleRef() {
        return roleRef;
    }

    public void setRoleRef(String value) {
        this.roleRef = value;
    }

    public Integer getSignoffQuorum() {
        return signoffQuorum;
    }

    public void setSignoffQuorum(Integer value) {
        this.signoffQuorum = value;
    }

    public String getTemplateRef() {
        return templateRef;
    }

    public void setTemplateRef(String value) {
        this.templateRef = value;
    }

    /***************
     * Customisation
     ***************/
    
    private RoleType role;
    private OrganisationType group;

    public RoleType getRole() {
        return role;
    }
    
    public void setRole(RoleType role) {
        this.role = role;
    }
    
    public OrganisationType getGroup() {
        return group;
    }
    
    public void setGroup(OrganisationType group) {
        this.group = group;
    }
}
