//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.UnusedRequiredTags;
/*
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
*/

/**
 * 
 *       This element represents a user defined enumeration value. 
 * 
 *       Attributes:
 * 
 *       value:          the enum value (required).
 *       listRef:        reference to a UserList element which gives the valid
 *                       values in the enum. 'value' must be one of these values.
 *       
 * 
 * <p>Java class for UserEnumDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserEnumDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="listRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "UserEnumDataType")
public class UserEnumDataType {

    //@XmlAttribute
    protected String listRef;
    //@XmlAttribute(required = true)
    protected String value;

    /**
     * Gets the value of the listRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListRef() {
        return listRef;
    }

    /**
     * Sets the value of the listRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListRef(String value) {
        this.listRef = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
