//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.07.22 at 11:41:15 AM EST
//


package tcav.plmxmlpdm.base;

import java.util.*;

import tcav.plmxmlpdm.TagTools;
import tcav.plmxmlpdm.TagTypeEnum;
import tcav.plmxmlpdm.type.UserDataType;
import tcav.plmxmlpdm.type.AssociatedDataSetType;
import tcav.plmxmlpdm.type.AssociatedFormType;
import tcav.plmxmlpdm.type.AssociatedFolderType;
import tcav.plmxmlpdm.type.ValidationResultsType;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;

/*
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
 */

/**
 *
 *       Base class for elements which have PLMXML Attributes, i.e. elements
 *       derived from plm:AttributeBase.
 *
 *       Attributes:
 *
 *       attributeRefs: reference to Attributes
 *
 *       Elements:
 *
 *       Attribute:     any element derived from AttributeBase.
 *
 *
 * <p>Java class for AttribOwnerBase complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AttribOwnerBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plmxml.org/Schemas/PLMXMLSchema}DescriptionBase">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.plmxml.org/Schemas/PLMXMLSchema}Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="attributeRefs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
//@XmlAccessorType(XmlAccessType.FIELD)
/*
  @XmlType(name = "AttribOwnerBase", propOrder = {
    "attribute"
})
 */
public abstract class AttribOwnerBase extends DescriptionBase {
    
    //@XmlElementRef(name = "Attribute", namespace = "http://www.plmxml.org/Schemas/PLMXMLSchema", type = JAXBElement.class)
    protected List<AttributeBase> attribute;
    
    //@XmlAttribute
    //@XmlIDREF
    protected List<Object> attributeRefs;
    
    private Hashtable<String, TagTypeEnum> idClassLookup;

    public AttribOwnerBase(Node node) {
        super(node);
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();
        
        idClassLookup = new Hashtable<String, TagTypeEnum>();
        
        TagTypeEnum tagType;
        for (int i=0; i<nodeList.getLength(); i++) {
            currentNode = nodeList.item(i);
            tagType = TagTypeEnum.fromValue(currentNode.getNodeName());
            
            switch(tagType) {
                case Arguments:
                case UserData:          
                    UserDataType ud = new UserDataType(currentNode);
                    getAttribute().add(ud);
                    idClassLookup.put(ud.getId(),tagType);
                    break;
                    
                case AssociatedDataSet:
                    AssociatedDataSetType ad = new AssociatedDataSetType(currentNode);
                    getAttribute().add(ad);
                    idClassLookup.put(ad.getId(),tagType);
                    break;
                    
                case AssociatedFolder:
                    AssociatedFolderType afd = new AssociatedFolderType(currentNode);
                    getAttribute().add(afd);
                    idClassLookup.put(afd.getId(),tagType);
                    break;
                    
                case AssociatedForm:
                    AssociatedFormType afm = new AssociatedFormType(currentNode);
                    getAttribute().add(afm);
                    idClassLookup.put(afm.getId(),tagType);
                    break;
                    
                case ValidationResults:
                    ValidationResultsType vr = new ValidationResultsType(currentNode);
                    getAttribute().add(vr);
                    idClassLookup.put(vr.getId(),tagType);
                    break;
                    
                default:
                    //System.out.println("AttribOwnerBase: "+currentNode.getNodeName());
                    break;
            }
        }
    }
    
    private String toStringId(String id){
        if(id.charAt(0)== '#')
            return id.substring(1);
        else
            return id;
    }
    
    private TagTypeEnum getAttributeClass(String id) {
        if(id == null || id.equals(""))
            return null;
        else
            return idClassLookup.get(toStringId(id));
        
    }

    public TagTypeEnum getAttributeClass(int index) {
        if(index >= getAttribute().size())
            return null;
        else
            return getAttributeClass(getAttribute().get(index).getId());
     
    }
    
    public AttributeBase getAttribute(String id){
        for(int i=0; i<getAttribute().size(); i++)
            if(getAttribute().get(i).getId().equals(toStringId(id)))
                return getAttribute().get(i);
        return null;
    }
    
    public int getAttributeIndex(String id){
        for(int i=0; i<getAttribute().size(); i++)
            if(getAttribute().get(i).getId().equals(toStringId(id)))
                return i;
        return -1;
    }
    
    public String getAttributeName(int index){
        if(index >= getAttribute().size())
            return null;
        
        String id = getAttribute().get(index).getId();
        switch(getAttributeClass(id)) {
            case Arguments:
            case UserData:
                return ((UserDataType)getAttribute().get(index)).getType();
                
            case AssociatedDataSet:
                return ((AssociatedDataSetType)getAttribute().get(index)).getRole();
                
            case AssociatedFolder:
                return ((AssociatedFolderType)getAttribute().get(index)).getRole();
                
            case AssociatedForm:
                return ((AssociatedFormType)getAttribute().get(index)).getRole();
                
            case ValidationResults:
                return ((ValidationResultsType)getAttribute().get(index)).getApplication();
                
            default:
                return null;
                
        }
    }
    
    /**
     * Gets the value of the attribute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AssociatedFormType }{@code >}
     * {@link JAXBElement }{@code <}{@link UserListDataType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkupType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBase }{@code >}
     * {@link JAXBElement }{@code <}{@link UserDataType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssociatedDataSetType }{@code >}
     * {@link JAXBElement }{@code <}{@link MassPropertiesType }{@code >}
     * {@link JAXBElement }{@code <}{@link EntityUserDataType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssociatedFolderType }{@code >}
     * {@link JAXBElement }{@code <}{@link ValidationResultsType }{@code >}
     *
     *
     */
    public List<AttributeBase> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<AttributeBase>();
        }
        return this.attribute;
    }
    
    /**
     * Gets the value of the attributeRefs property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeRefs property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeRefs().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     *
     *
     */
    public List<Object> getAttributeRefs() {
        if (attributeRefs == null) {
            attributeRefs = new ArrayList<Object>();
        }
        return this.attributeRefs;
    }
    
}
