//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:41:15 AM EST 
//


package tceav.manager.procedure.plmxmlpdm.type.element;

import tceav.xml.TagTools;
import tceav.manager.procedure.plmxmlpdm.ProcedureTagTypeEnum;
import tceav.manager.procedure.plmxmlpdm.base.AttributeBase;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import tceav.manager.procedure.plmxmlpdm.base.IdBase;

/**
 * 
 *       This element gives the result of a Validation Check performed on an object.
 *         
 *       Attributes:
 *       
 *       name:             name of the check
 *       result:           true if check passed, false if failed
 *       status:           an integer return code from the check
 *       comments:         a comment string
 *       adHoc:            true if the validation is ad-hoc.
 *       reportRef:        URI of the validation report file.
 *       
 * 
 * <p>Java class for ValidationCheckerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationCheckerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="adHoc" type="{http://www.w3.org/2001/XMLSchema}Boolean" />
 *       &lt;attribute name="comments" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reportRef" type="{http://www.plmxml.org/Schemas/PLMXMLSchema}anyURIType" />
 *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}Boolean" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "ValidationCheckerType")
public class ValidationCheckerType extends IdBase {

    //@XmlAttribute
    protected final String adHocAttribute = "adHoc";
    protected Boolean adHoc;
    
    //@XmlAttribute
    protected final String commentsAttribute = "comments";
    protected String comments;
    
    //@XmlAttribute
    protected final String nameAttribute = "name";
    protected String name;
    
    //@XmlAttribute
    protected final String reportRefAttribute = "reportRef";
    protected String reportRef;
    
    //@XmlAttribute
    protected final String resultAttribute = "result";
    protected Boolean result;
    
    //@XmlAttribute
    protected final String statusAttribute = "status";
    protected Integer status;
    
    
    
    public ValidationCheckerType(Node node) {
        Node currentNode = node;
        NamedNodeMap attrib = currentNode.getAttributes();
        NodeList nodeList = currentNode.getChildNodes();
        
        setAdHoc(TagTools.getBooleanValue(attrib, adHocAttribute));
        setResult(TagTools.getBooleanValue(attrib, resultAttribute));
        setStatus(TagTools.getIntegerValue(attrib, statusAttribute));
        setComments(TagTools.getStringValue(attrib, commentsAttribute));
        setName(TagTools.getStringValue(attrib, nameAttribute));
        setReportRef(TagTools.getStringValue(attrib, reportRefAttribute));
    }

    /**
     * Gets the value of the adHoc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdHoc() {
        return adHoc;
    }

    /**
     * Sets the value of the adHoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdHoc(Boolean value) {
        this.adHoc = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the reportRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportRef() {
        return reportRef;
    }

    /**
     * Sets the value of the reportRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportRef(String value) {
        this.reportRef = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResult(Boolean value) {
        this.result = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(Integer value) {
        this.status = value;
    }

}
